# Air is a popular live reloading tool for Go applications. 
# It is designed to automatically restart your Go application when it detects changes in the source code, 
# making the development process more efficient by eliminating the need to manually stop 
# and restart the application every time a change is made.

root = "." # The root directory of the project
temp_dir = "tmp" # The temporary directory where air will store its temporary file

[build] # The build configuration
    bin = "main" # The name of the binary file to be generated after building the project 
    cmd = "go build -o {{.Output}} {{.Input}}" # The command to build the project
    exclude = ["tmp/*", "client/*"] # Specifies the directories to be excluded from monotoring for changes
    inlcude = ["**/*.go"] # Specifies the file patterns to be inclided for monotoring
    ignore = ["tmp/*"] # Specifies the files or directories to be ignored when triggering a build. 

    